### ISSUE TITLE
타일채우기가 어려워요 ㅜ

### ISSUE THREAD

**Issue by soonmyeong2** [42somoim/42somoim5#1]
https://www.acmicpc.net/problem/2133

이 문제 어떻게 해결하셨나요?

**Comment by mimseong** [comment]
seongpar 문제 풀어 보러 달려갑니다 =3

**Comment by mimseong** [comment]
홀수 일 경우에는 구할 수 없으므로 0을 반환하고 

![image](https://user-images.githubusercontent.com/50068946/97252283-fd3ac380-184c-11eb-839e-b00da7f707d0.png)

짝수 일 경우를 생각하면 이런 규칙이 보입니다. 

2일 경우 3가지 4일 경우 2가지 6일 경우 2가지..

이렇게 새로운 타일이 나타납니다.

이제 크기 2 타일을 배치하고, 4타일을 배치하고, 6 타일을 배치하고 ... 타일을 배치하면서 갯수를 세주면 됩니다.

![image](https://user-images.githubusercontent.com/50068946/97252785-2740b580-184e-11eb-8b4c-0642a8b331fa.png)

3* f(n-2) +2*f(n-4) + 2*f(n-6) + ...

식을 세워보면 위처럼 나옵니다.

코드는 이렇게 짰어요!

```
#include <iostream>
#include <algorithm>
#include <vector>
#include <string>
#include <functional>
#include <string>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <cmath>
#include <cstring>
#include <bitset>

#define xx first
#define yy second
#define all(x) (x).begin(), (x).end()
#define MAXV 1000000

using namespace std;
using i64 = long long int;
using ii = pair<int, int>;
using ii64 = pair<i64, i64>;
using iii = tuple<int, int, int>;

int cache[35];

int     func(int n)
{
    if (n % 2 == 1)
        return 0;
    if (n == 0)
        return 1;
    if (n == 2)
        return 3;

    int& ret = cache[n];
    if (ret != -1)
        return ret;
    ret = 3 * func(n - 2);
    for (int i = n - 4; i >= 0; i -= 2)
        ret += 2 * func(i);
    return ret;
}

int     main()
{
    int n;
    scanf("%d", &n);

    memset(cache, -1, sizeof(cache));

    printf("%d\n", func(n));

    return 0;
}

```

**Comment by soonmyeong2** [comment]
미쳤다,,, 진짜 감사합니다 직접 다 그리신거예요?... 진짜 이해 쉽게 하고 가요 !! 감사해요! :):):)
